export enum RoomNames {
  ACT_ONE = 'ACT_ONE',
  ACT_TWO = 'ACT_TWO',
  ACT_THREE = 'ACT_THREE',
  ACT_FOUR = 'ACT_FOUR',

  BRANCH_ONE = 'BRANCH_ONE',
  BRANCH_TWO = 'BRANCH_TWO',
  BRANCH_THREE = 'BRANCH_THREE',
  BRANCH_FOUR = 'BRANCH_FOUR',

  Intermission = 'INTERMISSION',
  Tutorial = 'TUTORIAL',
}
