export enum ChestTypes {
  Small = 0,
  Locked = 1,
}

export enum EntityTypes {
  Chest = 'Chest',
  Item = 'Item',
  Doodad = 'Doodad',
  Bonfire = 'Bonfire',
  Grave = 'Grave',
  LoadSavePoint = 'LoadSavePoint',
  Boulder = 'Boulder',
  BoulderTrap = 'BoulderTrap',
  Spikes = 'Spikes',
  HoverText = 'HoverText',
  Trigger = 'Trigger',
  PendulumAxe = 'PendulumAxe',
  SawBlade = 'SawBlade',

  // monsters
  Bat = 'Bat',
  Goblin = 'Goblin',
  Slime = 'Slime',
  Crawler = 'Crawler',
  Divebomber = 'Divebomber',
  Lurker = 'Lurker',
  Mimic = 'Mimic',
  Cultist = 'Cultist',
  DemonKnight = 'DemonArmor',
  DemonDog = 'DemonDog',
  Spprigan = 'Spriggan',
  ManEatingPlant = 'ManeatingPlant',
  Spider = 'Spider',
  Harpy = 'Harpy',
  Thief = 'Thief',
  Wisp = 'Wisp',
  Golem = 'Golem',
  Zombie = 'Zombie',
  Hand = 'Hand',
  Ghost = 'Ghost',
  ElementalMage = 'ElementalMage',
  Juggernaut = 'Juggernaut',
  Swooper = 'Swooper',
  TikiMan = 'TikiMan',
  FireTortoise = 'Tortoise',
  FishMan = 'FishMan',
  Piranha = 'Piranha',
  FlyingMech = 'FlyingMech',

  // bosses
  GoblinKing = 'BossGoblin',
  BabyDragon = 'BossDragon',
  Worm = 'BossWorm',
  SprigganPlant = 'BossSpriggan',
  GolemBoss = 'BossGolem',
  WispBoss = 'BossWisp',
  Chimera = 'BossChimera',
  DemonMage = 'DemonMage',
  Necromancer = 'BossNecromancer',
  Abomination = 'BossAbomination',
  ZombieDragon = 'BossZombieDragon',
  ShadowKnight = 'BossShadowKnight',
  Behemoth = 'BossBehemoth',
  BroodDemon = 'BossBroodDemon',
  TowerSerpent = 'BossTowerSerpent',
  MechBoss = 'BossMech',
  FinalBoss = 'FinalBoss',
}

export enum ItemTypes {
  TreasureKey = 1,

  Sword = 49,
  Dagger = 45,
  Club = 55,
  MagicRod = 79,
  ShortBow = 93,

  MagicMappingScroll = 34,
  EnchantScroll = 35,
  TeleportScroll = 36,
  ChaosScroll = 37,
  RechargeScroll = 38,
  UncurseScroll = 39,
  IdentifyScroll = 40,
  JumpScroll = 41,

  Arrow = 3,
  ExplosiveArrow = 4,

  HealingPotion = 6,
  PoisonPotion = 7,
  WeightlessPotion = 8,
  QuicknessPotion = 9,
  HardeningPotion = 10,
  FeelStrongPotion = 11,
  MagicEmpoweringPotion = 12,
  StrPotion = 13,
  IntPotion = 14,
  DexPotion = 15,
  LukPotion = 16,
  VitPotion = 17,
  SpdPotion = 18,
  FireResistPotion = 19,
  ColdResistPotion = 20,
  ElectranceResistPotion = 21,
  PoisonResistPotion = 22,
  StrDebuffPotion = 23,
  IntDebuffPotion = 24,
  DexDebuffPotion = 25,
  LukDebuffPotion = 26,
  VitDebuffPotion = 27,
  FireResistDebuffPotion = 28,
  ColdResistDebuffPotion = 29,
  ElectranceResistDebuffPotion = 30,
  PoisonResistDebuffPotion = 31,
}
