export enum ChestTypes {
  Small = 0,
  Locked = 1,
}

export enum EntityTypes {
  Chest = 'Chest',
  Item = 'Item',
  Doodad = 'Doodad',
  Bonfire = 'Bonfire',
  Grave = 'Grave',
  LoadSavePoint = 'LoadSavePoint',
  BoulderTrap = 'BoulderTrap',
  HoverText = 'HoverText',
  Trigger = 'Trigger',

  // monsters
  Bat = 'Bat',
  Goblin = 'Goblin',
  Slime = 'Slime',
  Crawler = 'Crawler',
  Divebomber = 'Divebomber',
  Lurker = 'Lurker',
  Mimic = 'Mimic',
  Cultist = 'Cultist',
  DemonKnight = 'DemonArmor',
  DemonDog = 'DemonDog',
  Spprigan = 'Spriggan',
  ManEatingPlant = 'ManeatingPlant',
  Spider = 'Spider',
  Harpy = 'Harpy',
  Thief = 'Thief',
  Wisp = 'Wisp',
  Golem = 'Golem',
  Zombie = 'Zombie',
  Hand = 'Hand',
  Ghost = 'Ghost',
  ElementalMage = 'ElementalMage',
  Juggernaut = 'Juggernaut',
  Swooper = 'Swooper',
  TikiMan = 'TikiMan',
  FireTortoise = 'Tortoise',
  FishMan = 'FishMan',
  Piranha = 'Piranha',
  FlyingMech = 'FlyingMech',

  // bosses
  GoblinKing = 'BossGoblin',
  BabyDragon = 'BossDragon',
  Worm = 'BossWorm',
  SprigganPlant = 'BossSpriggan',
  GolemBoss = 'BossGolem',
  WispBoss = 'BossWisp',
  Chimera = 'BossChimera',
  DemonMage = 'DemonMage',
  Necromancer = 'BossNecromancer',
  Abomination = 'BossAbomination',
  ZombieDragon = 'BossZombieDragon',
  ShadowKnight = 'BossShadowKnight',
  Behemoth = 'BossBehemoth',
  BroodDemon = 'BossBroodDemon',
  TowerSerpent = 'BossTowerSerpent',
  MechBoss = 'BossMech',
  FinalBoss = 'FinalBoss',
}

export enum ItemTypes {
  TreasureKey = 1,

  Sword = 49,
  Dagger = 45,
  Club = 55,
  MagicRod = 78,

  MagicMappingScroll = 34,
  EnchantScroll = 35,
  TeleportScroll = 36,
  ChaosScroll = 37,
  RechargeScroll = 38,
  UncurseScroll = 39,
  IdentifyScroll = 40,
  JumpScroll = 41,

  Arrow = 5,
  ExplosiveArrow = 1,

  ColdResistancePotion = 20,
  NegativePoisonResistancePotion = 31,
  HealingPotion = 5,
  PoisonPotion = 6,
}
