export enum ChestTypes {
  Small = 0,
  Locked = 1,
}

export enum EntityTypes {
  Chest = 'Chest',
  Shop = 'Shop',
  Item = 'Item',
  Doodad = 'Doodad',
  Shrine = 'Shrine',
  Bonfire = 'Bonfire',
  Grave = 'Grave',
  LoadSavePoint = 'LoadSavePoint',
  Boulder = 'Boulder',
  BoulderTrap = 'BoulderTrap',
  Spikes = 'Spikes',
  HoverText = 'HoverText',
  Trigger = 'Trigger',
  PendulumAxe = 'PendulumAxe',
  SawBlade = 'SawBlade',

  // monsters
  Bat = 'Bat',
  Goblin = 'Goblin',
  Slime = 'Slime',
  Crawler = 'Crawler',
  Divebomber = 'Divebomber',
  Lurker = 'Lurker',
  Mimic = 'Mimic',
  Cultist = 'Cultist',
  DemonKnight = 'DemonArmor',
  DemonDog = 'DemonDog',
  Spprigan = 'Spriggan',
  ManEatingPlant = 'ManeatingPlant',
  Spider = 'Spider',
  Harpy = 'Harpy',
  Thief = 'Thief',
  Wisp = 'Wisp',
  Golem = 'Golem',
  Zombie = 'Zombie',
  Hand = 'Hand',
  Ghost = 'Ghost',
  ElementalMage = 'ElementalMage',
  Juggernaut = 'Juggernaut',
  Swooper = 'Swooper',
  TikiMan = 'TikiMan',
  FireTortoise = 'Tortoise',
  FishMan = 'FishMan',
  Piranha = 'Piranha',
  FlyingMech = 'FlyingMech',
  Samurai = 'MiniSamurai',

  // bosses
  GoblinKing = 'BossGoblin',
  BabyDragon = 'BossDragon',
  Worm = 'BossWorm',
  SprigganPlant = 'BossSpriggan',
  GolemBoss = 'BossGolem',
  WispBoss = 'BossWisp',
  Chimera = 'BossChimera',
  DemonMage = 'DemonMage',
  Necromancer = 'BossNecromancer',
  Abomination = 'BossAbomination',
  ZombieDragon = 'BossZombieDragon',
  ShadowKnight = 'BossShadowKnight',
  Behemoth = 'BossBehemoth',
  BroodDemon = 'BossBroodDemon',
  TowerSerpent = 'BossTowerSerpent',
  MechBoss = 'BossMech',
  FinalBoss = 'FinalBoss',
}

export enum ItemTypes {
  TreasureKey = 1,

  MagicMappingScroll = 34,
  EnchantScroll = 35,
  TeleportScroll = 36,
  ChaosScroll = 37,
  RechargeScroll = 38,
  UncurseScroll = 39,
  IdentifyScroll = 40,
  JumpScroll = 41,

  Arrow = 3,
  ExplosiveArrow = 4,

  HealingPotion = 6,
  PoisonPotion = 7,
  FeatherfallPotion = 8,
  QuicknessPotion = 9,
  DefensePotion = 10,
  VigorPotion = 11,
  MagicPotion = 12,
  StrPotion = 13,
  IntPotion = 14,
  DexPotion = 15,
  LukPotion = 16,
  VitPotion = 17,
  SpdPotion = 18,
  FireResistPotion = 19,
  ColdResistPotion = 20,
  ElectranceResistPotion = 21,
  PoisonResistPotion = 22,
  StrDebuffPotion = 23,
  IntDebuffPotion = 24,
  DexDebuffPotion = 25,
  LukDebuffPotion = 26,
  VitDebuffPotion = 27,
  FireResistDebuffPotion = 28,
  ColdResistDebuffPotion = 29,
  ElectranceResistDebuffPotion = 30,
  PoisonResistDebuffPotion = 31,

  // wand 
  LightningWand = 68,
  FireWand = 69,
  IceWand = 70,
  WandOfChaos = 71,
  WandOfBlink = 72,
  WandOfPestilence = 73,
  WandOfDigging = 74,
  WandOfHealing = 75,
  BrokenWand = 76,

  // dagger 
  Dagger = 45,
  Baselard = 46,
  GlassBlade = 47,
  BlinkDagger = 89,
  
  // sword  
  CopperSword = 49,
  SteelSword = 50,
  BroadSword = 51,
  DragonSlayer = 52,
  BoneSword = 53,

  // club
  WoodenClub = 55,
  Hammer = 56,
  FlangedMace = 57,
  MorningStart = 58,
  WarHammer = 59,
  Bludgeon = 60,
  SpearheadedBaton = 61,
  Flail = 62,
  ThunderGodsHammer = 90,
  
  // axe
  WoodsmanAxe = 64,
  BattleAxe = 65,

  // rod
  MagicRod = 79,
  SpacerRod = 80,
  WaveRod = 81,

  // spear
  Spear = 83,

  // cqc
  Caestus = 85,
  Claw = 86,
  Qatar = 87,

  // bow
  ShortBow = 93,
  LongBow = 94,
  CrossBow = 95,
  ArmCannon = 96,

  // Other ranged
  Bomb = 100,
  Boomerang = 101,
  EnchantedBoomerang = 102,
  ThrowingDagger = 104,

  // amulet
  Kerchief = 107,
  CrossAmulet = 108,
  MonsterTooth = 109,
  MagicStone = 110,
  Compass = 111,
  BirdAmulet = 112,
  FeatherTalisman = 113,
  Scarf = 114,
  SkullNecklace = 115,
  Locket = 116,
  StuddedCollar = 117,
  ShrunkenHead = 118,
  LionTalisman = 119,
  PocketWatch = 120,
  WiseManBeard = 121,
  Scarab = 122,

  // chest
  BreastPlate = 155,
  TravelerTunic = 156,
  Robes = 157,
  AnimalSkin = 158,
  ReinforcedArmor = 159,
  RangerUniform = 160,
  AcolyteRobes = 161,
  DruidCloak = 162,
  FullPlateArmor = 163,
  LeatherArmor = 164,
  HighPriestRobes = 165,
  BeserkerArmor = 166,
  HalfPlate = 167,
  AssassinLeathers = 168,
  ConjurerRobes = 169,
  GoldPlate = 170,

  // cap
  WoodenHelm = 123,
  OldHood = 124,
  WizardHat = 125,
  BoarHead = 126,
  StuddedHelm = 127,
  VagabondCap = 128,
  BirdMask = 129,
  RocHead = 130,
  GreatHelm = 131,
  FlatCap = 132,
  DemonMask = 133,
  WolfHead = 134,
  RoyalCrown = 135,
  AssassinHood = 136,
  LunarCirclet = 137,
  DragonHead = 138,

  // boots
  PageGreaves = 171,
  PeddlerBoots = 172,
  PeasantShoes = 173,
  FighterSandals = 174,
  MercenaryGreaves = 175,
  HighwaymanBoots = 176,
  MageShoes = 177,
  ColosseumClogs = 178,
  KnightGreaves = 179,
  BanditBoots = 180,
  WarlockShoes = 181,
  SavageSandals = 182,
  ChampionGreaves = 183,
  AssassinBoots = 184,
  WitchBoots = 185,
  DragonSlayerBoots = 186,

  // rings
  IncompleteRing = 139,
  Ring = 140,
  DamagedRing = 141,
  GemStuddedRing = 142,
  WoodRing = 143,
  LeafRing = 144,
  FlowerRing = 145,
  SunRing = 146,
  BoneRing = 147,
  SkullRing = 148,
  StarRing = 149,
  ShieldRing = 150,
  MisteryRing = 151,
  SwordRing = 152,
  MoonRing = 153,
  EyeRing = 154,

  // gloves
  PageGloves = 187,
  PeddlerMits = 188,
  ApprenticeGloves = 188,
  FighterGloves = 190,
  KnightGauntlets = 191,
  ThiefGloves = 192,
  MysticGloves = 193,
  GladiatorGloves = 194,
  CrusaderGloves = 195,
  RogueGloves = 196,
  VoodooGloves = 197,
  SavageGloves = 198,
  ChampionGauntlets = 199,
  MasterThiefGloves = 200,
  SageGloves = 201,
  DragonSlayerGloves = 202,

  Chicken = 224,

  GrapplingHook = 212,
  Book = 216,
  RuneOrb1 = 218,
  RuneOrb2 = 219,
  RuneOrb3 = 220,
  RuneOrb4 = 221,

  RoastedChicken = 224,
  RottenChicken = 225,
  CookedEye = 226,
  Sashimi = 227,
  Candy = 228,
  PorkChop = 217,

  WeaponStart = 45,
  WeaponEnd = 90,
  BowStart = 93,
  BowEnd = 95,
  OtherRangedStart = 101,
  OtherRangedEnd = 104,
}

export enum DoodadTypes {
  Dummy = 18,
  Table = 1,
}

export enum ShrineTypes {
  Deranged = 0,
  Death = 1,
  Well = 2,
  Forge = 3,
  GodCurse = 4,
  Scholar = 5,
}

export enum BookTypes {
  Dash = 0,
  FireShield = 1,
  Blink = 2,
  Iceball = 3,
  Fireball = 4,
  Lightning = 5,
  ChainLightning = 6,
  Spirits = 7,
  MagicMissile = 8,
  Shockwave = 9,
  Eleclance = 10,
  FrostNova = 11,
  FlamePillar = 12,
  EvilTransformation = 13,
  Charm = 14,
  SummonMonster = 15,
}

export enum AttributeTypes {
  WeaponLifeSteal = 'ATTRIBUTE_LIFE_STEAL',
  WeaponEmitsSpirits = 'ATTRIBUTE_EMITS_SPIRITS',
  WeaponKnockback = 'ATTRIBUTE_KNOCKBACK',
  WeaponFairyFire = 'ATTRIBUTE_FAIRY_FIRE',
  WeaponSlowStrike = 'ATTRIBUTE_SLOW_ON_STRIKE',
  WeaponBlink = 'ATTRIBUTE_BLINK',
  WeaponLightning = 'ATTRIBUTE_LIGHTNING',
  WeaponMidas = 'ATTRIBUTE_MIDAS',
  WeaponSplashAttack = 'ATTRIBUTE_SPLASH_ATTACK',
  WeaponStrongPoison = 'ATTRIBUTE_STRONG_POISON',
  WeaponPoisonCoat = 'ATTRIBUTE_WEAPON_POISON',
  
  AllWeaponBurn = 'ATTRIBUTE_BURN',
  AllWeaponFreeze = 'ATTRIBUTE_FREEZE',
  AllWeaponShock = 'ATTRIBUTE_SHOCK',
  
  BowWeightless = 'ATTRIBUTE_ARROW_NO_GRAVITY',
  BowLight = 'ATTRIBUTE_ARROW_LIGHT',
  BowTrajectory = 'ATTRIBUTE_ARROW_TRAJECTORY',
  BowMulti = 'ATTRIBUTE_ARROW_MULTI',
  BowHomingArrow = 'ATTRIBUTE_HOMING_ARROW',
  
  Berserk = 'ATTRIBUTE_BERSERK',
  DoubleJump = 'ATTRIBUTE_DOUBLE_JUMP',
  TrippleJump = 'ATTRIBUTE_TRIPPLE_JUMP',  
  FireWalk = 'ATTRIBUTE_FIRE_WALK',  
  Bouncy = 'ATTRIBUTE_BOUNCY',  
  SuperSpeed = 'ATTRIBUTE_SUPER_SPEED',  
  GrabWalls = 'ATTRIBUTE_GRAB_WALLS',  
  ThrowHard = 'ATTRIBUTE_THROWING',  
  TrueSight = 'ATTRIBUTE_TRUE_SIGHT',  
  FamiliarShooter = 'ATTRIBUTE_FAMILIAR_SHOOTER',  
  FamiliarHealer = 'ATTRIBUTE_FAMILIAR_HEALER',  
  FamiliarMelee = 'ATTRIBUTE_FAMILIAR_MELEE',  
  LightRadius = 'ATTRIBUTE_LIGHT_RADIUS',  
  JumpDamage = 'ATTRIBUTE_JUMP_DAMAGE',  
  HeavySink = 'ATTRIBUTE_HEAVY',  
  JumpHigh = 'ATTRIBUTE_JUMP_SPEED',  
  WalkChargeDamage = 'ATTRIBUTE_WALK_CHARGE_DAMAGE',  
  SwimLikeFish = 'ATTRIBUTE_SWIM',  
  BreathUnderWater = 'ATTRIBUTE_BREATH_UNDERWATER',  
  FeatherFall = 'ATTRIBUTE_FEATHERFALL',  
  LightFeet = 'ATTRIBUTE_SNEAKY',  
  PhaseVertical = 'ATTRIBUTE_PHASE_VERTICAL',  
  PhaseHorizontal = 'ATTRIBUTE_PHASE_HORIZONTAL',  
  Merchant = 'ATTRIBUTE_MERCHANT',  
  BoulderProtection = 'ATTRIBUTE_HARD_HEAD',  
  SlowAura = 'ATTRIBUTE_SLOW_AURA',  
  FreezeAura = 'ATTRIBUTE_FREEZE_AURA',  
  FlameAura = 'ATTRIBUTE_FLAME_AURA',  
  Greedy = 'ATTRIBUTE_GREEDY',  
  Slaying = 'ATTRIBUTE_SLAYING',  
  HeavyPunch = 'ATTRIBUTE_PUNCH',  
  Archery = 'ATTRIBUTE_RANGE_FOCUS',  
  CoinHeal = 'ATTRIBUTE_COIN_HEAL',  
  BurnReflect = 'ATTRIBUTE_ARMOR_BURN',  
  ShockReflect = 'ATTRIBUTE_ARMOR_SHOCK',  
  FreezeReflect = 'ATTRIBUTE_ARMOR_FREEZE',  
  PoisonReflect = 'ATTRIBUTE_ARMOR_POISON',  
  DamageReflect = 'ATTRIBUTE_ARMOR_REFLECT',  
  SpiritsReflect = 'ATTRIBUTE_ARMOR_SPIRITS',  
  MistReflect = 'ATTRIBUTE_ARMOR_INCORPOREAL',  
  SpikeProtection = 'ATTRIBUTE_SPIKE_BREAKING',  
  FlappyJump = 'ATTRIBUTE_FLAPPY_JUMP',  
  RepulseAttackers = 'ATTRIBUTE_REPULSE_ATTACKERS',  
  ProjectileDeflection = 'ATTRIBUTE_PROJECTILE_DEFLECTION',  
  ReachUpgrade = 'ATTRIBUTE_WEAPON_REACH',  
  FamiliarMaster = 'ATTRIBUTE_FAMILIAR_MASTER', 
  Zygox = 'ATTRIBUTE_ZYGOX', 
  Seltioc = 'ATTRIBUTE_SELTIOC', 
  GodCurse = 'ATTRIBUTE_GOD_CURSE', 

  ArmorDA = 'ATTRIBUTE_MORTAL',  
  AmuletReincarnate = 'ATTRIBUTE_REINCARNATE',  
  BootsFireJump = 'ATTRIBUTE_FIRE_JUMP',  
  CapSpellCost = 'ATTRIBUTE_SPELL_COST_REDUCTION',  
  ArmorMagicShield = 'ATTRIBUTE_MAGIC_SHIELD',  
  GloveExplosionAffinity = 'ATTRIBUTE_EXPLOSION_AFFINITY',  
  RingChestSpirits = 'ATTRIBUTE_CHEST_SPIRITS',  
  RingChestHeal = 'ATTRIBUTE_CHEST_HEAL',  
  SwordMagicPogo = 'ATTRIBUTE_MAGIC_POGO',

  Str = 'ATTRIBUTE_STR',
  Dex = 'ATTRIBUTE_DEX',
  Vit = 'ATTRIBUTE_VIT',
  Spd = 'ATTRIBUTE_SPD',
  Int = 'ATTRIBUTE_INT',
  Luk = 'ATTRIBUTE_LUK',
  Def = 'ATTRIBUTE_DEFENSE',
  Sta = 'ATTRIBUTE_STA',
  
  ResistFire = 'ATTRIBUTE_RESIST_FIRE',
  ResistCold = 'ATTRIBUTE_RESIST_COLD',
  ResistPoison = 'ATTRIBUTE_RESIST_POISON',
  ResistElec = 'ATTRIBUTE_RESIST_ELEC',
  ResistAll = 'ATTRIBUTE_RESIST_ALL',
}
